version: "3.3"
services:
  bates:
    image: "rex"
    volumes:
      - bates:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
  bickle:
    image: "bickle"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  voorhies:
    image: "voorhies"
    depends_on:
      - bates
    restart: unless-stopped
volumes:
  bates:
